
'''
grade_goal5 = int(input("กรอกเป้าหมาย GPAX 5 เทอม (Ex. 2.25,3.50) : "))
grade_goal6 = int(input("กรอกเป้าหมาย GPAX 6 เทอม (Ex. 2.25,3.50) : "))
'''

def science_m4(): #วิทย์ ม.4 เทอม 1,2
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai = float(input("ภาษาไทยพื้นฐาน : "))
    thai = float(input_grade_thai*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_economics = float(input("เศรษฐศาสตร์ : "))
    economics = float(input_grade_economics*1.0)
    input_grade_pe1 = float(input("สุขศึกษา : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art_music = float(input("ศิลปะ/ดนตรี : "))
    art_music = float(input_grade_art_music*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. : "))
    techno = float(input_grade_techno*0.5)
    input_grade_fun_eng = float(input("Fundamental English : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_math = float(input("คณิตศาสตร์ : "))
    math = float(input_grade_math*1.5)
    input_grade_physics = float(input("วิทยาศาสตร์ (ฟิสิกส์) : "))
    physics = float(input_grade_physics*1.5)
    input_grade_chemistry = float(input("วิทยาศาสตร์ (เคมี) : "))
    chemistry = float(input_grade_chemistry*1.5)
    input_grade_biology = float(input("วิทยาศาสตร์ (ชีวะ) : "))
    biology = float(input_grade_biology*1.5)
    input_grade_astronomy = float(input("โลก ดาราศาสตร์และอวกาศ : "))
    astronomy = float(input_grade_astronomy*1.0)
    input_grade_pe2 = float(input("พลศึกษา : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_dev_eng = float(input("Developmental English : "))
    dev_eng = float(input_grade_dev_eng*1.0)

def health_science(): #วิทย์-สุขภาพ ม.5,6 ห้อง 1 เทอม 1,2
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai = float(input("ภาษาไทยพื้นฐาน : "))
    thai = float(input_grade_thai*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_economics = float(input("เศรษฐศาสตร์ : "))
    economics = float(input_grade_economics*1.0)
    input_grade_pe1 = float(input("สุขศึกษา : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art_music = float(input("ศิลปะ/ดนตรี : "))
    art_music = float(input_grade_art_music*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. : "))
    techno = float(input_grade_techno*0.5)
    input_grade_fun_eng = float(input("Fundamental English : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_math = float(input("คณิตศาสตร์ : "))
    math = float(input_grade_math*1.5)
    input_grade_physics = float(input("วิทยาศาสตร์ (ฟิสิกส์) : "))
    physics = float(input_grade_physics*1.5)
    input_grade_chemistry = float(input("วิทยาศาสตร์ (เคมี) : "))
    chemistry = float(input_grade_chemistry*1.5)
    input_grade_biology = float(input("วิทยาศาสตร์ (ชีวะ) : "))
    biology = float(input_grade_biology*1.5)
    input_grade_astronomy = float(input("โลก ดาราศาสตร์และอวกาศ : "))
    astronomy = float(input_grade_astronomy*1.0)
    input_grade_pe2 = float(input("พลศึกษา : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_dev_eng = float(input("Developmental English : "))
    dev_eng = float(input_grade_dev_eng*1.0)
    
    print("กลุ่มสาระการเรียนรู้เพิ่มเติม (เลือกเสรี)")
    input_grade_math_aptitude = float(input("ความถนัดทางคณิตศาสตร์ : "))
    math_aptitude = float(input_grade_math_aptitude*0.5)
    input_grade_cell_bio_molecule = float(input("เซลล์/ชีววิทยาโมเลกุล : "))
    cell_bio_molecule = float(input_grade_cell_bio_molecule*1.0)
    input_grade_english_for_medical = float(input("ภาษาอังกฤษสำหรับวิทยาศาสตร์และการแพทย์ : "))
    english_for_medical = float(input_grade_english_for_medical*0.5)

def applied_science(): #วิทย์-ประยุกต์ ม.5,6 ห้อง 2,3 เทอม 1,2
    
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai = float(input("ภาษาไทยพื้นฐาน : "))
    thai = float(input_grade_thai*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_economics = float(input("เศรษฐศาสตร์ : "))
    economics = float(input_grade_economics*1.0)
    input_grade_pe1 = float(input("สุขศึกษา : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art_music = float(input("ศิลปะ/ดนตรี : "))
    art_music = float(input_grade_art_music*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. : "))
    techno = float(input_grade_techno*0.5)
    input_grade_fun_eng = float(input("Fundamental English : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_math = float(input("คณิตศาสตร์ : "))
    math = float(input_grade_math*1.5)
    input_grade_physics = float(input("วิทยาศาสตร์ (ฟิสิกส์) : "))
    physics = float(input_grade_physics*1.5)
    input_grade_chemistry = float(input("วิทยาศาสตร์ (เคมี) : "))
    chemistry = float(input_grade_chemistry*1.5)
    input_grade_biology = float(input("วิทยาศาสตร์ (ชีวะ) : "))
    biology = float(input_grade_biology*1.5)
    input_grade_astronomy = float(input("โลก ดาราศาสตร์และอวกาศ : "))
    astronomy = float(input_grade_astronomy*1.0)
    input_grade_pe2 = float(input("พลศึกษา : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_dev_eng = float(input("Developmental English : "))
    dev_eng = float(input_grade_dev_eng*1.0)
    
    print("กลุ่มสาระการเรียนรู้เพิ่มเติม (เลือกเสรี)")
    input_grade_math_aptitude = float(input("ความถนัดทางคณิตศาสตร์ : "))
    math_aptitude = float(input_grade_math_aptitude*0.5)
    input_grade_engineer_skill = float(input("ทักษะเชิงวิศวกรรม : "))
    engineer_skill = float(input_grade_engineer_skill*1.0)
    input_grade_english_for_test = float(input("ภาษาอังกฤษสำหรับข้อสอบวัดมาตรฐาน : "))
    english_for_test = float(input_grade_english_for_test*0.5)

def amsp_science(): #วิทย์-ทั่วไป ม.5,6 ห้อง 4 เทอม 1,2
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai = float(input("ภาษาไทยพื้นฐาน : "))
    thai = float(input_grade_thai*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_economics = float(input("เศรษฐศาสตร์ : "))
    economics = float(input_grade_economics*1.0)
    input_grade_pe1 = float(input("สุขศึกษา : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art_music = float(input("ศิลปะ/ดนตรี : "))
    art_music = float(input_grade_art_music*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. : "))
    techno = float(input_grade_techno*0.5)
    input_grade_fun_eng = float(input("Fundamental English : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_math = float(input("คณิตศาสตร์ : "))
    math = float(input_grade_math*1.5)
    input_grade_physics = float(input("วิทยาศาสตร์ (ฟิสิกส์) : "))
    physics = float(input_grade_physics*1.5)
    input_grade_chemistry = float(input("วิทยาศาสตร์ (เคมี) : "))
    chemistry = float(input_grade_chemistry*1.5)
    input_grade_biology = float(input("วิทยาศาสตร์ (ชีวะ) : "))
    biology = float(input_grade_biology*1.5)
    input_grade_astronomy = float(input("โลก ดาราศาสตร์และอวกาศ : "))
    astronomy = float(input_grade_astronomy*1.0)
    input_grade_pe2 = float(input("พลศึกษา : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_dev_eng = float(input("Developmental English : "))
    dev_eng = float(input_grade_dev_eng*1.0)
    
    print("กลุ่มสาระการเรียนรู้เพิ่มเติม (เลือกเสรี)")
    input_grade_math_aptitude = float(input("ความถนัดทางคณิตศาสตร์ : "))
    math_aptitude = float(input_grade_math_aptitude*0.5)
    input_grade_extra_science = float(input("วิทยาศาสตร์เพิ่มพูน : "))
    extra_science = float(input_grade_extra_science*1.0)
    input_grade_english_for_test = float(input("ภาษาอังกฤษสำหรับข้อสอบวัดมาตรฐาน : "))
    english_for_test = float(input_grade_english_for_test*0.5)

def inter_science(): #วิทย์-อินเตอร์ ม.5,6 ห้อง 5 เทอม 1,2
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai = float(input("ภาษาไทยพื้นฐาน : "))
    thai = float(input_grade_thai*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_economics = float(input("เศรษฐศาสตร์ : "))
    economics = float(input_grade_economics*1.0)
    input_grade_pe1 = float(input("สุขศึกษา : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art_music = float(input("ศิลปะ/ดนตรี : "))
    art_music = float(input_grade_art_music*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. : "))
    techno = float(input_grade_techno*0.5)
    input_grade_fun_eng = float(input("Fundamental English : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_math = float(input("คณิตศาสตร์ : "))
    math = float(input_grade_math*1.5)
    input_grade_physics = float(input("วิทยาศาสตร์ (ฟิสิกส์) : "))
    physics = float(input_grade_physics*1.5)
    input_grade_chemistry = float(input("วิทยาศาสตร์ (เคมี) : "))
    chemistry = float(input_grade_chemistry*1.5)
    input_grade_biology = float(input("วิทยาศาสตร์ (ชีวะ) : "))
    biology = float(input_grade_biology*1.5)
    input_grade_astronomy = float(input("โลก ดาราศาสตร์และอวกาศ : "))
    astronomy = float(input_grade_astronomy*1.0)
    input_grade_pe2 = float(input("พลศึกษา : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_dev_eng = float(input("Developmental English : "))
    dev_eng = float(input_grade_dev_eng*1.0)
    
    print("กลุ่มสาระการเรียนรู้เพิ่มเติม (เลือกเสรี)")
    input_grade_sat_math = float(input("SAT MATH : "))
    sat_math = float(input_grade_sat_math*0.5)
    input_grade_advanced_science = float(input("SG Advanced Science : "))
    advanced_science = float(input_grade_advanced_science*0.5)
    input_grade_international_english = float(input("อังกฤษในแบบสอบวัดระดับนานาชาติ : "))
    international_english = float(input_grade_international_english*1.0)

def art_m4_term1(): #ศิลป์ ม.4 เทอม 1 ห้อง 6,7 
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai1 = float(input("ภาษาไทยพื้นฐาน : "))
    thai1 = float(input_grade_thai1*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_history = float(input("ประวัติศาสตร์ พื้นฐาน : "))
    history = float(input_grade_history*1.0)
    input_grade_pe1 = float(input("สุขศึกษา : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art_music = float(input("ศิลปะ/ดนตรี : "))
    art_music = float(input_grade_art_music*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. : "))
    techno = float(input_grade_techno*0.5)
    input_grade_fun_eng = float(input("Fundamental English : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_extra_thai2 = float(input("ภาษาไทยเพิ่มเติม : "))
    thai2 = float(input_grade_extra_thai2*2.0)
    input_grade_extra_math = float(input("คณิตศาสตร์เพิ่มเติม : "))
    extra_math = float(input_grade_extra_math*1.5)
    input_grade_thai_civilization = float(input("อารยธรรมไทย : "))
    thai_civilization = float(input_grade_thai_civilization*2.0)
    input_grade_pe2 = float(input("พลศึกษา : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_dev_eng = float(input("Developmental English : "))
    dev_eng = float(input_grade_dev_eng*2.0)

def art_m4_term2(): #ศิลป์ ม.4 เทอม 2 ห้อง 6,7
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai1 = float(input("ภาษาไทยพื้นฐาน : "))
    thai1 = float(input_grade_thai1*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_civic_duty = float(input("หน้าที่พลเมือง : "))
    civic_duty = float(input_grade_civic_duty*1.0)
    input_grade_pe1 = float(input("สุขศึกษา : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art_music = float(input("ศิลปะ/ดนตรี : "))
    art_music = float(input_grade_art_music*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. : "))
    techno = float(input_grade_techno*0.5)
    input_grade_fun_eng = float(input("Fundamental English : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_extra_thai2 = float(input("ภาษาไทยเพิ่มเติม : "))
    thai2 = float(input_grade_extra_thai2*2.0)
    input_grade_extra_math = float(input("คณิตศาสตร์เพิ่มเติม : "))
    extra_math = float(input_grade_extra_math*1.5)
    input_grade_sea_study = float(input("โลกเอเชียตะวันออกเฉียงใต้ศึกษา : "))
    sea_study = float(input_grade_sea_study*2.0)
    input_grade_pe2 = float(input("พลศึกษา : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_dev_eng = float(input("Developmental English : "))
    dev_eng = float(input_grade_dev_eng*2.0)

def cal_art_term1(): #ศิลป์-คำนวณ ม.5 ม.6 ห้อง 6 เทอม 1
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai1 = float(input("ภาษาไทย : "))
    thai1 = float(input_grade_thai1*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_economy = float(input("เศรษศาสตร์ : "))
    economy = float(input_grade_economy*1.0)
    input_grade_pe1 = float(input("สุขศึกษา : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art = float(input("ศิลปะ : "))
    art = float(input_grade_art*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. : "))
    techno = float(input_grade_techno*0.5)
    input_grade_fun_eng = float(input("Fundamental English : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_extra_thai2 = float(input("ภาษาไทยเพิ่มเติม : "))
    thai2 = float(input_grade_extra_thai2*2.0)
    input_grade_math = float(input("คณิตศาสตร์ : "))
    math = float(input_grade_math*1.5)
    input_grade_history = float(input("ปริทัศน์ประวัติศาสตร์ : "))
    history = float(input_grade_history*2.0)
    input_grade_pe2 = float(input("พลศึกษา : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_dev_eng = float(input("Developmental English : "))
    dev_eng = float(input_grade_dev_eng*2.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม (เสรี)")
    input_grade_thai_for_business = float(input("ภาษาไทยเพื่อกิจธุระทางวิชาชีพ : "))
    thai_for_business = float(input_grade_thai_for_business*0.5)
    input_grade_math_aptitude = float(input("ความถนัดทางคณิตศาสตร์ : "))
    math_aptitude = float(input_grade_math_aptitude*1.0)
    input_grade_english_for_test = float(input("ภาษาอังกฤษสำหรับข้อสอบวัดมาตรฐาน : "))
    english_for_test = float(input_grade_english_for_test*1.0)

def cal_art_term2(): #ศิลป์-คำนวณ ม.5 ม.6 ห้อง 6 เทอม 2
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai1 = float(input("ภาษาไทย : "))
    thai1 = float(input_grade_thai1*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_economy1 = float(input("เศรษศาสตร์ : "))
    economy1 = float(input_grade_economy1*1.0)
    input_grade_pe1 = float(input("สุขศึกษา : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art = float(input("ศิลปะ : "))
    art = float(input_grade_art*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. : "))
    techno = float(input_grade_techno*0.5)
    input_grade_fun_eng = float(input("Fundamental English : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_thai2 = float(input("ภาษาไทย : "))
    thai2 = float(input_grade_thai2*2.0)
    input_grade_math = float(input("คณิตศาสตร์ : "))
    math = float(input_grade_math*1.5)
    input_grade_economy2 = float(input("เศรษศาสตร์ : "))
    economy2 = float(input_grade_economy2*2.0)
    input_grade_pe2 = float(input("พลศึกษา : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_dev_eng = float(input("Developmental English : "))
    dev_eng = float(input_grade_dev_eng*2.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม (เสรี)")
    input_grade_thai_for_business = float(input("ภาษาไทยเพื่อกิจธุระทางวิชาชีพ : "))
    thai_for_business = float(input_grade_thai_for_business*0.5)
    input_grade_math_aptitude = float(input("ความถนัดทางคณิตศาสตร์ : "))
    math_aptitude = float(input_grade_math_aptitude*1.0)
    input_grade_english_for_test = float(input("ภาษาอังกฤษสำหรับข้อสอบวัดมาตรฐาน : "))
    english_for_test = float(input_grade_english_for_test*1.0)

def social_art_term1(): #ศิลป์-สังคม ม.5 ม.6 ห้อง 7 เทอม 1
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai1 = float(input("ภาษาไทย : "))
    thai1 = float(input_grade_thai1*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_economy1 = float(input("เศรษศาสตร์ : "))
    economy1 = float(input_grade_economy1*1.0)
    input_grade_pe1 = float(input("สุขศึกษา : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art = float(input("ศิลปะ : "))
    art = float(input_grade_art*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. : "))
    techno = float(input_grade_techno*0.5)
    input_grade_fun_eng = float(input("Fundamental English : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_extra_thai2 = float(input("ภาษาไทยเพิ่มเติม : "))
    extra_thai2 = float(input_grade_extra_thai2*2.0)
    input_grade_math = float(input("คณิตศาสตร์ : "))
    math = float(input_grade_math*1.5)
    input_grade_history = float(input("ปริทัศน์ประวัติศาสตร์ : "))
    history = float(input_grade_history*2.0)
    input_grade_pe2 = float(input("พลศึกษา : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_dev_eng = float(input("Developmental English : "))
    dev_eng = float(input_grade_dev_eng*2.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม (เสรี)")
    input_grade_thai_for_business = float(input("ภาษาไทยเพื่อกิจธุระทางวิชาชีพ : "))
    thai_for_business = float(input_grade_thai_for_business*0.5)
    input_grade_social_human = float(input("มนุษย์กับสังคม : "))
    social_human = float(input_grade_social_human*1.0)
    input_grade_english_for_test = float(input("ภาษาอังกฤษสำหรับข้อสอบวัดมาตรฐาน : "))
    english_for_test = float(input_grade_english_for_test*1.0)

def social_art_term2(): #ศิลป์-สังคม ม.5 ม.6 ห้อง 7 เทอม 2
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai1 = float(input("ภาษาไทย : "))
    thai1 = float(input_grade_thai1*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_economy1 = float(input("เศรษศาสตร์ : "))
    economy1 = float(input_grade_economy1*1.0)
    input_grade_pe1 = float(input("สุขศึกษา : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art = float(input("ศิลปะ : "))
    art = float(input_grade_art*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. : "))
    techno = float(input_grade_techno*0.5)
    input_grade_fun_eng = float(input("Fundamental English : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_thai2 = float(input("ภาษาไทย : "))
    thai2 = float(input_grade_thai2*2.0)
    input_grade_math = float(input("คณิตศาสตร์ : "))
    math = float(input_grade_math*1.5)
    input_grade_economy2 = float(input("เศรษศาสตร์ : "))
    economy2 = float(input_grade_economy2*2.0)
    input_grade_pe2 = float(input("พลศึกษา : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_dev_eng = float(input("Developmental English : "))
    dev_eng = float(input_grade_dev_eng*2.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม (เสรี)")
    input_grade_thai_for_business = float(input("ภาษาไทยเพื่อกิจธุระทางวิชาชีพ : "))
    thai_for_business = float(input_grade_thai_for_business*0.5)
    input_grade_religion = float(input("ศาสนาเปรียบเทียบ : "))
    religion = float(input_grade_religion*1.0)
    input_grade_english_for_test = float(input("ภาษาอังกฤษสำหรับข้อสอบวัดมาตรฐาน : "))
    english_for_test = float(input_grade_english_for_test*1.0)

def japanese_art_m4_term1(): #สหศิลป์-ญี่ปุ่น ม.4 ห้อง 8 เทอม 1
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai1 = float(input("ภาษาไทยพื้นฐาน : "))
    thai1 = float(input_grade_thai1*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_history = float(input("ประวัติศาสตร์พื้นฐาน : "))
    history = float(input_grade_history*1.0)
    input_grade_pe1 = float(input("สุขศึกษา : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art = float(input("ศิลปะ : "))
    art = float(input_grade_art*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. : "))
    techno = float(input_grade_techno*0.5)
    input_grade_fun_eng = float(input("Fundamental English : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_extra_thai2 = float(input("ภาษาไทยเพิ่มเติม : "))
    extra_thai2 = float(input_grade_extra_thai2*2.0)
    input_grade_thai_civilization = float(input("อารยธรรมไทย : "))
    thai_civilization = float(input_grade_thai_civilization*1.5)
    input_grade_pe2 = float(input("พลศึกษา : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_japan = float(input("ภาษาญี่ปุ่น : "))
    japan = float(input_grade_japan*3.0)
    input_grade_dev_eng = float(input("Developmental English : "))
    dev_eng = float(input_grade_dev_eng*2.0)
    
def japanese_art_m4_term2(): #สหศิลป์-ญี่ปุ่น ม.4 ห้อง 8 เทอม 2
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai1 = float(input("ภาษาไทยพื้นฐาน : "))
    thai1 = float(input_grade_thai1*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_civic_duty = float(input("หน้าที่พลเมือง : "))
    civic_duty = float(input_grade_civic_duty*1.0)
    input_grade_pe1 = float(input("สุขศึกษา : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art = float(input("ศิลปะ : "))
    art = float(input_grade_art*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. : "))
    techno = float(input_grade_techno*0.5)
    input_grade_fun_eng = float(input("Fundamental English : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_extra_thai2 = float(input("ภาษาไทยเพิ่มเติม : "))
    extra_thai2 = float(input_grade_extra_thai2*2.0)
    input_grade_sea_study = float(input("โลกเอเชี่ยตะวันออกเฉียงใต้ศึกษา : "))
    sea_study = float(input_grade_sea_study*1.5)
    input_grade_pe2 = float(input("พลศึกษา : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_japan = float(input("ภาษาญี่ปุ่น : "))
    japan = float(input_grade_japan*3.0)
    input_grade_dev_eng = float(input("Developmental English : "))
    dev_eng = float(input_grade_dev_eng*2.0)

def japanese_art_m5m6_term1(): #สหศิลป์-ญี่ปุ่น ม.5,6 ห้อง 8 เทอม 1
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai1 = float(input("ภาษาไทยพื้นฐาน : "))
    thai1 = float(input_grade_thai1*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_economy = float(input("เศรษศาสตร์ : "))
    economy = float(input_grade_economy*1.0)
    input_grade_pe1 = float(input("สุขศึกษา : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art = float(input("ศิลปะ : "))
    art = float(input_grade_art*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. : "))
    techno = float(input_grade_techno*0.5)
    input_grade_fun_eng = float(input("Fundamental English : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_extra_thai2 = float(input("ภาษาไทยเพิ่มเติม : "))
    extra_thai2 = float(input_grade_extra_thai2*2.0)
    input_grade_history2 = float(input("ปริทัศน์ประวัติศาสตร์ : "))
    history2 = float(input_grade_history2*1.5)
    input_grade_pe2 = float(input("พลศึกษา : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_japan = float(input("ภาษาญี่ปุ่น : "))
    japan = float(input_grade_japan*3.0)
    input_grade_dev_eng = float(input("Developmental English : "))
    dev_eng = float(input_grade_dev_eng*2.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_japan2 = float(input("ภาษาญี่ปุ่น : "))
    japan2 = float(input_grade_japan2*1.0)

def japanese_art_m5m6_term2(): #สหศิลป์-ญี่ปุ่น ม.5,6 ห้อง 8 เทอม 2
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai1 = float(input("ภาษาไทยพื้นฐาน : "))
    thai1 = float(input_grade_thai1*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_history = float(input("ประวัติศาสตร์ พื้นฐาน : "))
    history = float(input_grade_history*1.0)
    input_grade_pe1 = float(input("สุขศึกษา : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art = float(input("ศิลปะ : "))
    art = float(input_grade_art*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. : "))
    techno = float(input_grade_techno*0.5)
    input_grade_fun_eng = float(input("Fundamental English : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_extra_thai2 = float(input("ภาษาไทยเพิ่มเติม : "))
    extra_thai2 = float(input_grade_extra_thai2*2.0)
    input_grade_economy = float(input("เศรษศาสตร์ : "))
    economy = float(input_grade_economy*1.5)
    input_grade_pe2 = float(input("พลศึกษา : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_japan = float(input("ภาษาญี่ปุ่น : "))
    japan = float(input_grade_japan*3.0)
    input_grade_dev_eng = float(input("Developmental English : "))
    dev_eng = float(input_grade_dev_eng*2.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_japan2 = float(input("ภาษาญี่ปุ่น : "))
    japan2 = float(input_grade_japan2*1.0)

def chinese_art_m4_term1(): #สหศิลป์-จีน ม.4 ห้อง 8 เทอม 1
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai1 = float(input("ภาษาไทยพื้นฐาน : "))
    thai1 = float(input_grade_thai1*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_history = float(input("ประวัติศาสตร์พื้นฐาน : "))
    history = float(input_grade_history*1.0)
    input_grade_pe1 = float(input("สุขศึกษา : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art = float(input("ศิลปะ : "))
    art = float(input_grade_art*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. : "))
    techno = float(input_grade_techno*0.5)
    input_grade_fun_eng = float(input("Fundamental English : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_extra_thai2 = float(input("ภาษาไทยเพิ่มเติม : "))
    extra_thai2 = float(input_grade_extra_thai2*2.0)
    input_grade_thai_civilization = float(input("อารยธรรมไทย : "))
    thai_civilization = float(input_grade_thai_civilization*1.5)
    input_grade_pe2 = float(input("พลศึกษา : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_chinese = float(input("ภาษาจีน : "))
    chinese = float(input_grade_chinese*3.0)
    input_grade_dev_eng = float(input("Developmental English : "))
    dev_eng = float(input_grade_dev_eng*2.0)
    
def chinese_art_m4_term2(): #สหศิลป์-จีน ม.4 ห้อง 8 เทอม 2
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai1 = float(input("ภาษาไทยพื้นฐาน : "))
    thai1 = float(input_grade_thai1*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_civic_duty = float(input("หน้าที่พลเมือง : "))
    civic_duty = float(input_grade_civic_duty*1.0)
    input_grade_pe1 = float(input("สุขศึกษา : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art = float(input("ศิลปะ : "))
    art = float(input_grade_art*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. : "))
    techno = float(input_grade_techno*0.5)
    input_grade_fun_eng = float(input("Fundamental English : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_extra_thai2 = float(input("ภาษาไทยเพิ่มเติม : "))
    extra_thai2 = float(input_grade_extra_thai2*2.0)
    input_grade_sea_study = float(input("โลกเอเชี่ยตะวันออกเฉียงใต้ศึกษา : "))
    sea_study = float(input_grade_sea_study*1.5)
    input_grade_pe2 = float(input("พลศึกษา : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_chinese = float(input("ภาษาจีน : "))
    chinese = float(input_grade_chinese*3.0)
    input_grade_dev_eng = float(input("Developmental English : "))
    dev_eng = float(input_grade_dev_eng*2.0)

def chinese_art_m5m6_term1(): #สหศิลป์-จีน ม.5,6 ห้อง 8 เทอม 1
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai1 = float(input("ภาษาไทยพื้นฐาน : "))
    thai1 = float(input_grade_thai1*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_economy = float(input("เศรษศาสตร์ : "))
    economy = float(input_grade_economy*1.0)
    input_grade_pe1 = float(input("สุขศึกษา : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art = float(input("ศิลปะ : "))
    art = float(input_grade_art*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. : "))
    techno = float(input_grade_techno*0.5)
    input_grade_fun_eng = float(input("Fundamental English : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_extra_thai2 = float(input("ภาษาไทยเพิ่มเติม : "))
    extra_thai2 = float(input_grade_extra_thai2*2.0)
    input_grade_history2 = float(input("ปริทัศน์ประวัติศาสตร์ : "))
    history2 = float(input_grade_history2*1.5)
    input_grade_pe2 = float(input("พลศึกษา : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_chinese = float(input("ภาษาจีน : "))
    chinese = float(input_grade_chinese*3.0)
    input_grade_dev_eng = float(input("Developmental English : "))
    dev_eng = float(input_grade_dev_eng*2.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_chinese2 = float(input("ภาษาจีน : "))
    chinese2 = float(input_grade_chinese2*1.0)

def chinese_art_m5m6_term2(): #สหศิลป์-จีน ม.5,6 ห้อง 8 เทอม 2
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai1 = float(input("ภาษาไทยพื้นฐาน : "))
    thai1 = float(input_grade_thai1*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_history = float(input("ประวัติศาสตร์ พื้นฐาน : "))
    history = float(input_grade_history*1.0)
    input_grade_pe1 = float(input("สุขศึกษา : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art = float(input("ศิลปะ : "))
    art = float(input_grade_art*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. : "))
    techno = float(input_grade_techno*0.5)
    input_grade_fun_eng = float(input("Fundamental English : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_extra_thai2 = float(input("ภาษาไทยเพิ่มเติม : "))
    extra_thai2 = float(input_grade_extra_thai2*2.0)
    input_grade_economy = float(input("เศรษศาสตร์ : "))
    economy = float(input_grade_economy*1.5)
    input_grade_pe2 = float(input("พลศึกษา : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_chinese = float(input("ภาษาจีน : "))
    chinese = float(input_grade_chinese*3.0)
    input_grade_dev_eng = float(input("Developmental English : "))
    dev_eng = float(input_grade_dev_eng*2.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_chinese2 = float(input("ภาษาจีน : "))
    chinese2 = float(input_grade_chinese2*1.0)

def german_art_m4_term1(): #สหศิลป์-เยอรมัน ม.4 ห้อง 8 เทอม 1
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai1 = float(input("ภาษาไทยพื้นฐาน : "))
    thai1 = float(input_grade_thai1*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_history = float(input("ประวัติศาสตร์พื้นฐาน : "))
    history = float(input_grade_history*1.0)
    input_grade_pe1 = float(input("สุขศึกษา : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art = float(input("ศิลปะ : "))
    art = float(input_grade_art*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. : "))
    techno = float(input_grade_techno*0.5)
    input_grade_fun_eng = float(input("Fundamental English : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_extra_thai2 = float(input("ภาษาไทยเพิ่มเติม : "))
    extra_thai2 = float(input_grade_extra_thai2*2.0)
    input_grade_thai_civilization = float(input("อารยธรรมไทย : "))
    thai_civilization = float(input_grade_thai_civilization*1.5)
    input_grade_pe2 = float(input("พลศึกษา : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_german = float(input("ภาษาเยอรมัน : "))
    german = float(input_grade_german*3.0)
    input_grade_dev_eng = float(input("Developmental English : "))
    dev_eng = float(input_grade_dev_eng*2.0)
    
def german_art_m4_term2(): #สหศิลป์-เยอรมัน ม.4 ห้อง 8 เทอม 2
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai1 = float(input("ภาษาไทยพื้นฐาน : "))
    thai1 = float(input_grade_thai1*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_civic_duty = float(input("หน้าที่พลเมือง : "))
    civic_duty = float(input_grade_civic_duty*1.0)
    input_grade_pe1 = float(input("สุขศึกษา : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art = float(input("ศิลปะ : "))
    art = float(input_grade_art*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. : "))
    techno = float(input_grade_techno*0.5)
    input_grade_fun_eng = float(input("Fundamental English : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_extra_thai2 = float(input("ภาษาไทยเพิ่มเติม : "))
    extra_thai2 = float(input_grade_extra_thai2*2.0)
    input_grade_sea_study = float(input("โลกเอเชี่ยตะวันออกเฉียงใต้ศึกษา : "))
    sea_study = float(input_grade_sea_study*1.5)
    input_grade_pe2 = float(input("พลศึกษา : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_german = float(input("ภาษาเยอรมัน : "))
    german = float(input_grade_german*3.0)
    input_grade_dev_eng = float(input("Developmental English : "))
    dev_eng = float(input_grade_dev_eng*2.0)
    
def german_art_m5m6_term1(): #สหศิลป์-เยอรมัน ม.5,6 ห้อง 8 เทอม 1
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai1 = float(input("ภาษาไทยพื้นฐาน : "))
    thai1 = float(input_grade_thai1*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_economy = float(input("เศรษศาสตร์ : "))
    economy = float(input_grade_economy*1.0)
    input_grade_pe1 = float(input("สุขศึกษา : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art = float(input("ศิลปะ : "))
    art = float(input_grade_art*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. : "))
    techno = float(input_grade_techno*0.5)
    input_grade_fun_eng = float(input("Fundamental English : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_extra_thai2 = float(input("ภาษาไทยเพิ่มเติม : "))
    extra_thai2 = float(input_grade_extra_thai2*2.0)
    input_grade_history2 = float(input("ปริทัศน์ประวัติศาสตร์ : "))
    history2 = float(input_grade_history2*1.5)
    input_grade_pe2 = float(input("พลศึกษา : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_german = float(input("ภาษาเยอรมัน : "))
    german = float(input_grade_german*3.0)
    input_grade_dev_eng = float(input("Developmental English : "))
    dev_eng = float(input_grade_dev_eng*2.0)
    
    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_german2 = float(input("ภาษาเยอรมัน : "))
    german2 = float(input_grade_german2*3.0)

def german_art_m5m6_term2(): #สหศิลป์-เยอรมัน ม.5,6 ห้อง 8 เทอม 2
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai1 = float(input("ภาษาไทยพื้นฐาน : "))
    thai1 = float(input_grade_thai1*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_history = float(input("ประวัติศาสตร์ พื้นฐาน : "))
    history = float(input_grade_history*1.0)
    input_grade_pe1 = float(input("สุขศึกษา : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art = float(input("ศิลปะ : "))
    art = float(input_grade_art*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. : "))
    techno = float(input_grade_techno*0.5)
    input_grade_fun_eng = float(input("Fundamental English : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_extra_thai2 = float(input("ภาษาไทยเพิ่มเติม : "))
    extra_thai2 = float(input_grade_extra_thai2*2.0)
    input_grade_economy = float(input("เศรษศาสตร์ : "))
    economy = float(input_grade_economy*1.5)
    input_grade_pe2 = float(input("พลศึกษา : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_german = float(input("ภาษาเยอรมัน : "))
    german = float(input_grade_german*3.0)
    input_grade_dev_eng = float(input("Developmental English : "))
    dev_eng = float(input_grade_dev_eng*2.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_german2 = float(input("ภาษาเยอรมัน : "))
    german2 = float(input_grade_german2*3.0)

def music_art_m4_term1(): #สหศิลป์-ดนตรี ม.4 ห้อง 8 เทอม 1
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai1 = float(input("ภาษาไทยพื้นฐาน : "))
    thai1 = float(input_grade_thai1*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_history = float(input("ประวัติศาสตร์พื้นฐาน : "))
    history = float(input_grade_history*1.0)
    input_grade_pe1 = float(input("สุขศึกษา : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art = float(input("ศิลปะ : "))
    art = float(input_grade_art*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. : "))
    techno = float(input_grade_techno*0.5)
    input_grade_fun_eng = float(input("Fundamental English : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_extra_thai2 = float(input("ภาษาไทยเพิ่มเติม : "))
    extra_thai2 = float(input_grade_extra_thai2*2.0)
    input_grade_thai_civilization = float(input("อารยธรรมไทย : "))
    thai_civilization = float(input_grade_thai_civilization*1.5)
    input_grade_pe2 = float(input("พลศึกษา : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_music = float(input("ดนตรี : "))
    music = float(input_grade_music*3.0)
    input_grade_dev_eng = float(input("Developmental English : "))
    dev_eng = float(input_grade_dev_eng*2.0)
    
def music_art_m4_term2(): #สหศิลป์-ดนตรี ม.4 ห้อง 8 เทอม 2
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai1 = float(input("ภาษาไทยพื้นฐาน : "))
    thai1 = float(input_grade_thai1*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_civic_duty = float(input("หน้าที่พลเมือง : "))
    civic_duty = float(input_grade_civic_duty*1.0)
    input_grade_pe1 = float(input("สุขศึกษา : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art = float(input("ศิลปะ : "))
    art = float(input_grade_art*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. : "))
    techno = float(input_grade_techno*0.5)
    input_grade_fun_eng = float(input("Fundamental English : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_extra_thai2 = float(input("ภาษาไทยเพิ่มเติม : "))
    extra_thai2 = float(input_grade_extra_thai2*2.0)
    input_grade_sea_study = float(input("โลกเอเชี่ยตะวันออกเฉียงใต้ศึกษา : "))
    sea_study = float(input_grade_sea_study*1.5)
    input_grade_pe2 = float(input("พลศึกษา : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_music = float(input("ดนตรี : "))
    music = float(input_grade_music*3.0)
    input_grade_dev_eng = float(input("Developmental English : "))
    dev_eng = float(input_grade_dev_eng*2.0)
     
def music_art_m5m6_term1(): #สหศิลป์-ดนตรี ม.5,6 ห้อง 8 เทอม 1
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai1 = float(input("ภาษาไทยพื้นฐาน : "))
    thai1 = float(input_grade_thai1*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_economy = float(input("เศรษศาสตร์ : "))
    economy = float(input_grade_economy*1.0)
    input_grade_pe1 = float(input("สุขศึกษา : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art = float(input("ศิลปะ : "))
    art = float(input_grade_art*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. : "))
    techno = float(input_grade_techno*0.5)
    input_grade_fun_eng = float(input("Fundamental English : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_extra_thai2 = float(input("ภาษาไทยเพิ่มเติม : "))
    extra_thai2 = float(input_grade_extra_thai2*2.0)
    input_grade_history2 = float(input("ปริทัศน์ประวัติศาสตร์ : "))
    history2 = float(input_grade_history2*1.5)
    input_grade_pe2 = float(input("พลศึกษา : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_music = float(input("ดนตรี : "))
    music = float(input_grade_music*3.0)
    input_grade_dev_eng = float(input("Developmental English : "))
    dev_eng = float(input_grade_dev_eng*2.0)
    
    
    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_music2 = float(input("ดนตรี : "))
    music2 = float(input_grade_music2*1.0)

def music_art_m5m6_term2(): #สหศิลป์-ดนตรี ม.5,6 ห้อง 8 เทอม 2
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai1 = float(input("ภาษาไทยพื้นฐาน : "))
    thai1 = float(input_grade_thai1*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_history = float(input("ประวัติศาสตร์ พื้นฐาน : "))
    history = float(input_grade_history*1.0)
    input_grade_pe1 = float(input("สุขศึกษา : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art = float(input("ศิลปะ : "))
    art = float(input_grade_art*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. : "))
    techno = float(input_grade_techno*0.5)
    input_grade_fun_eng = float(input("Fundamental English : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_extra_thai2 = float(input("ภาษาไทยเพิ่มเติม : "))
    extra_thai2 = float(input_grade_extra_thai2*2.0)
    input_grade_economy = float(input("เศรษศาสตร์ : "))
    economy = float(input_grade_economy*1.5)
    input_grade_pe2 = float(input("พลศึกษา : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_music = float(input("ดนตรี : "))
    music = float(input_grade_music*3.0)
    input_grade_dev_eng = float(input("Developmental English : "))
    dev_eng = float(input_grade_dev_eng*2.0)
    
    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_music2 = float(input("ดนตรี : "))
    music2 = float(input_grade_music2*1.0)

def acting_art_m4_term1(): #สหศิลป์-การแสดง ม.4 ห้อง 8 เทอม 1
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai1 = float(input("ภาษาไทยพื้นฐาน : "))
    thai1 = float(input_grade_thai1*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_history = float(input("ประวัติศาสตร์พื้นฐาน : "))
    history = float(input_grade_history*1.0)
    input_grade_pe1 = float(input("สุขศึกษา : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art = float(input("ศิลปะ : "))
    art = float(input_grade_art*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. : "))
    techno = float(input_grade_techno*0.5)
    input_grade_fun_eng = float(input("Fundamental English : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_extra_thai2 = float(input("ภาษาไทยเพิ่มเติม : "))
    extra_thai2 = float(input_grade_extra_thai2*2.0)
    input_grade_thai_civilization = float(input("อารยธรรมไทย : "))
    thai_civilization = float(input_grade_thai_civilization*1.5)
    input_grade_pe2 = float(input("พลศึกษา : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_acting_art = float(input("ศิลปะ : "))
    acting_art = float(input_grade_acting_art*3.0)
    input_grade_dev_eng = float(input("Developmental English : "))
    dev_eng = float(input_grade_dev_eng*2.0)
    
def acting_art_m4_term2(): #สหศิลป์-การแสดง ม.4 ห้อง 8 เทอม 2
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai1 = float(input("ภาษาไทยพื้นฐาน : "))
    thai1 = float(input_grade_thai1*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_civic_duty = float(input("หน้าที่พลเมือง : "))
    civic_duty = float(input_grade_civic_duty*1.0)
    input_grade_pe1 = float(input("สุขศึกษา : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art = float(input("ศิลปะ : "))
    art = float(input_grade_art*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. : "))
    techno = float(input_grade_techno*0.5)
    input_grade_fun_eng = float(input("Fundamental English : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_extra_thai2 = float(input("ภาษาไทยเพิ่มเติม : "))
    extra_thai2 = float(input_grade_extra_thai2*2.0)
    input_grade_sea_study = float(input("โลกเอเชี่ยตะวันออกเฉียงใต้ศึกษา : "))
    sea_study = float(input_grade_sea_study*1.5)
    input_grade_pe2 = float(input("พลศึกษา : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_acting_art = float(input("ศิลปะ : "))
    acting_art = float(input_grade_acting_art*3.0)
    input_grade_dev_eng = float(input("Developmental English : "))
    dev_eng = float(input_grade_dev_eng*2.0)
     
def acting_art_m5m6_term1(): #สหศิลป์-การแสดง ม.5,6 ห้อง 8 เทอม 1
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai1 = float(input("ภาษาไทยพื้นฐาน : "))
    thai1 = float(input_grade_thai1*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_economy = float(input("เศรษศาสตร์ : "))
    economy = float(input_grade_economy*1.0)
    input_grade_pe1 = float(input("สุขศึกษา : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art = float(input("ศิลปะ : "))
    art = float(input_grade_art*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. : "))
    techno = float(input_grade_techno*0.5)
    input_grade_fun_eng = float(input("Fundamental English : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_extra_thai2 = float(input("ภาษาไทยเพิ่มเติม : "))
    extra_thai2 = float(input_grade_extra_thai2*2.0)
    input_grade_history2 = float(input("ปริทัศน์ประวัติศาสตร์ : "))
    history2 = float(input_grade_history2*1.5)
    input_grade_pe2 = float(input("พลศึกษา : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_acting_art = float(input("ศิลปะ : "))
    acting_art = float(input_grade_acting_art*3.0)
    input_grade_dev_eng = float(input("Developmental English : "))
    dev_eng = float(input_grade_dev_eng*2.0)
    
    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_acting_art = float(input("ศิลปะ : "))
    acting_art = float(input_grade_acting_art*1.0)

def acting_art_m5m6_term2(): #สหศิลป์-การแสดง ม.5,6 ห้อง 8 เทอม 2
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai1 = float(input("ภาษาไทยพื้นฐาน : "))
    thai1 = float(input_grade_thai1*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_history = float(input("ประวัติศาสตร์ พื้นฐาน : "))
    history = float(input_grade_history*1.0)
    input_grade_pe1 = float(input("สุขศึกษา : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art = float(input("ศิลปะ : "))
    art = float(input_grade_art*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. : "))
    techno = float(input_grade_techno*0.5)
    input_grade_fun_eng = float(input("Fundamental English : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_extra_thai2 = float(input("ภาษาไทยเพิ่มเติม : "))
    extra_thai2 = float(input_grade_extra_thai2*2.0)
    input_grade_economy = float(input("เศรษศาสตร์ : "))
    economy = float(input_grade_economy*1.5)
    input_grade_pe2 = float(input("พลศึกษา : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_acting_art = float(input("ศิลปะ : "))
    acting_art = float(input_grade_acting_art*3.0)
    input_grade_dev_eng = float(input("Developmental English : "))
    dev_eng = float(input_grade_dev_eng*2.0)
    
    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_acting_art = float(input("ศิลปะ : "))
    acting_art = float(input_grade_acting_art*1.0)

def smap_m4_term1(): #พสพ ม.4 เทอม 1
    

print('''
โปรแกรมนี้เป็นโปรแกรมที่จะนำข้อมูลเกรดของคุณไปคำนวณหา 
-GPAX 5,6 ภาคเรียน 
-คำนวณ GPA ตามกลุ่มสาระ
-คำนวณหาเกรดเฉลี่ยขั้นต่ำเพื่อบรรลุเป้าหมายเกรดที่ต้องการเมื่อจบการศึกษา
''')
print('''0 : สายการเรียน วิทยาศาสตร์-ทั่วไป")
1 : แผนการเรียน วิทยาศาสตร์-สุขภาพ
2 : แผนการเรียน วิทยาศาสตร์-ประยุกต์
3 : แผนการเรียน วิทยาศาสตร์-อินเตอร์
4 : แผนการเรียน สหศิลป์-จีน
5 : แผนการเรียน สหศิลป์-ญี่ปุ่น
6 : แผนการเรียน สหศิลป์-เยอรมัน
7 : แผนการเรียน สหศิลป์-การแสดง
8 : แผนการเรียน สหศิลป์-สังคม
9 : แผนการเรียน สหศิลป์-คำนวณ
''')

learning_path = input("พิมพ์ตัวเลข(1-9) เพื่อเลือกสายการเรียนของคุณ : ")



if learning_path == 1:
    print("")
    



