""" elif learning_path == 12:
    print("=======================================================================")
    print(f"กรอกข้อมูลเกรดเฉลี่ย ม.4 เทอม 1")
    user_information_list.append(smap_m4_term1())
    print("=======================================================================")
    print(f"กรอกข้อมูลเกรดเฉลี่ย ม.4 เทอม 2")
    user_information_list.append(smap_m4_term2())
    print("=======================================================================")
    print(f"กรอกข้อมูลเกรดเฉลี่ย ม.5 เทอม 1")
    user_information_list.append(smap_m5_term1())
    print("=======================================================================")
    print(f"กรอกข้อมูลเกรดเฉลี่ย ม.5 เทอม 2")
    user_information_list.append(smap_m5_term2())
    user_information_list.append(smap_no_bug())
    user_information_list.append(smap_no_bug())
 """

def smap_m4_term1(): #พสพ ม.4 เทอม 1
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai = float(input("ภาษาไทยพื้นฐาน (ท31101) : "))
    thai = float(input_grade_thai*1.0)
    input_grade_thai2 = float(input("ภาษาไทยพื้นฐาน (ท31102) : "))
    thai2 = float(input_grade_thai2*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. (ค31101) : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_math_ie2 = float(input("คณิตศาสตร์ IE. (ค31102) : "))
    math_ie2 = float(input_grade_math_ie2*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี (ว31107) : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_tech_design2 = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี (ว31108) : "))
    tech_design2 = float(input_grade_tech_design2*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. (ว31101) : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_sci_tech2 = float(input("วิทยาศาสตร์และเทคโนโลยี IE. (ว31102) : "))
    sci_tech2 = float(input_grade_sci_tech2*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. (ส31101) : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_social_ie2 = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. (ส31103) : "))
    social_ie2 = float(input_grade_social_ie2*1.0)
    input_grade_history = float(input("ประวัติศาสตร์พื้นฐาน (ส31102) : "))
    history = float(input_grade_history*1.0)
    input_grade_civic_duty = float(input("หน้าที่พลเมือง (ส31104) : "))
    civic_duty = float(input_grade_civic_duty*1.0)
    input_grade_pe1 = float(input("สุขศึกษา (พ31101) : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_pe12 = float(input("สุขศึกษา (พ31102) : "))
    pe12 = float(input_grade_pe12*0.5)
    input_grade_art = float(input("ศิลปะ (ศ31101) : "))
    art = float(input_grade_art*0.5)
    input_grade_art_music = float(input("ศิลปะศึกษาและดนตรีศึกษา (ศ31102) : "))
    art_music = float(input_grade_art_music*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. (ง31101) : "))
    techno = float(input_grade_techno*0.5)
    input_grade_techno2 = float(input("การงานอาชีพ IE. (ง31102) : "))
    techno2 = float(input_grade_techno2*0.5)
    input_grade_fun_eng = float(input("Fundamental English (อ31101) : "))
    fun_eng = float(input_grade_fun_eng*1.0)
    input_grade_fun_eng2 = float(input("Fundamental English (อ31102) : "))
    fun_eng2 = float(input_grade_fun_eng2*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_extra_math = float(input("คณิตศาสตร์เพิ่มเติม (ค31201) : "))
    extra_math = float(input_grade_extra_math*1.5)
    input_grade_extra_math2 = float(input("คณิตศาสตร์เพิ่มเติม (ค31202) : "))
    extra_math2 = float(input_grade_extra_math2*1.5)
    input_grade_physic = float(input("วิทยาศาสตร์(ฟิสิกส์) (ว31201) : "))
    physic = float(input_grade_physic*1.5)
    input_grade_physic2 = float(input("วิทยาศาสตร์(ฟิสิกส์) (ว31202) : "))
    physic2 = float(input_grade_physic2*1.5)
    input_grade_chemcical = float(input("วิทยาศาสตร์(เคมี) (ว31221) : "))
    chemcical = float(input_grade_chemcical*1.5)
    input_grade_biology = float(input("วิทยาศาสตร์(ชีววิทยา) (ว31241) : "))
    biology = float(input_grade_biology*1.5)
    input_grade_biology2 = float(input("วิทยาศาสตร์(ชีววิทยา) (ว31242) : "))
    biology2 = float(input_grade_biology2*1.5)
    input_grade_astronomy = float(input("โลก ดาราศาสตร์ และอวกาศ (ว31261) : "))
    astronomy = float(input_grade_astronomy*1.0)
    input_grade_pe2 = float(input("พลศึกษา (พ31201) : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_pe22 = float(input("พลศึกษา (พ31202) : "))
    pe22 = float(input_grade_pe22*0.5)
    input_grade_dev_eng = float(input("Developmental English (อ31201) : "))
    dev_eng = float(input_grade_dev_eng*1.0)

def smap_m4_term2(): #พสพ ม.4 เทอม 2
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai = float(input("ภาษาไทยพื้นฐาน (ท32103) : "))
    thai = float(input_grade_thai*1.0)
    input_grade_thai2 = float(input("ภาษาไทยพื้นฐาน (ท32104) : "))
    thai2 = float(input_grade_thai2*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. (ค32103) : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_math_ie2 = float(input("คณิตศาสตร์ IE. (ค32104) : "))
    math_ie2 = float(input_grade_math_ie2*1.0)
    input_grade_tech_design = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี (ว32109) : "))
    tech_design = float(input_grade_tech_design*0.5)
    input_grade_tech_design2 = float(input("วิทยาการคำนวณ/การออกแบบเทคโนโลยี (ว32110) : "))
    tech_design2 = float(input_grade_tech_design2*0.5)
    input_grade_sci_tech = float(input("วิทยาศาสตร์และเทคโนโลยี IE. (ว32103) : "))
    sci_tech = float(input_grade_sci_tech*1.0)
    input_grade_sci_tech2 = float(input("วิทยาศาสตร์และเทคโนโลยี IE. (ว32104) : "))
    sci_tech2 = float(input_grade_sci_tech2*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. (ส32105) : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_social_ie2 = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. (ส32107) : "))
    social_ie2 = float(input_grade_social_ie2*1.0)
    input_grade_religion = float(input("ศาสนา (ส32108) : "))
    religion = float(input_grade_religion*1.0)
    input_grade_economy = float(input("เศรษศาสตร์ (ส32106) : "))
    economy = float(input_grade_economy*1.0)
    input_grade_pe1 = float(input("สุขศึกษา (พ32103) : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_pe12 = float(input("สุขศึกษา (พ32104) : "))
    pe12 = float(input_grade_pe12*0.5)
    input_grade_art = float(input("ศิลปะ (ศ32103) : "))
    art = float(input_grade_art*0.5)
    input_grade_art_music = float(input("ศิลปะศึกษาและดนตรีศึกษา (ศ32104) : "))
    art_music = float(input_grade_art_music*0.5)
    input_grade_techno = float(input("การงานอาชีพ IE. (ง32103) : "))
    techno = float(input_grade_techno*0.5)
    input_grade_techno2 = float(input("การงานอาชีพ IE. (ง32104) : "))
    techno2 = float(input_grade_techno2*0.5)
    input_grade_fun_eng = float(input("Fundamental English (อ32103) : "))
    fun_eng = float(input_grade_fun_eng*1.0)
    input_grade_fun_eng2 = float(input("Fundamental English (อ32104) : "))
    fun_eng2 = float(input_grade_fun_eng2*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_math = float(input("คณิตศาสตร์ (ค32203) : "))
    math = float(input_grade_math*1.5)
    input_grade_physic = float(input("วิทยาศาสตร์(ฟิสิกส์) (ว32203) : "))
    physic = float(input_grade_physic*1.5)
    input_grade_chemcical = float(input("วิทยาศาสตร์(เคมี) (ว31222) : "))
    chemcical = float(input_grade_chemcical*1.5)
    input_grade_chemcical2 = float(input("วิทยาศาสตร์(เคมี) (ว32223) : "))
    chemcical2 = float(input_grade_chemcical2*1.5)
    input_grade_biology = float(input("วิทยาศาสตร์(ชีววิทยา) (ว32243) : "))
    biology = float(input_grade_biology*1.5)
    input_grade_astronomy = float(input("โลก ดาราศาสตร์ และอวกาศ (ว31262) : "))
    astronomy = float(input_grade_astronomy*1.0)
    input_grade_astronomy2 = float(input("โลก ดาราศาสตร์ และอวกาศ (ว32263) : "))
    astronomy2 = float(input_grade_astronomy2*1.0)
    input_grade_pe2 = float(input("พลศึกษา (พ31201) : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_pe22 = float(input("พลศึกษา (พ31202) : "))
    pe22 = float(input_grade_pe22*0.5)
    input_grade_dev_eng = float(input("Developmental English (อ31201) : "))
    dev_eng = float(input_grade_dev_eng*1.0)

def smap_m5_term1(): #พสพ ม.5 เทอม 1
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai = float(input("ภาษาไทยพื้นฐาน (ท33105) : "))
    thai = float(input_grade_thai*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. (ค33105) : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_science = float(input("วิทยาศาสตร์ IE. (ว33105) : "))
    science = float(input_grade_science*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. (ส33109) : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_geography = float(input("ภูมิศาสตร์และเหตุการณ์ปัจจุบัน (ส33110) : "))
    geography = float(input_grade_geography*1.0)
    input_grade_pe1 = float(input("สุขศึกษา (พ31105) : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art = float(input("ศิลปะ (ศ33105) : "))
    art = float(input_grade_art*0.5)
    input_grade_techno = float(input("การงานอาชีพและเทคโนโลยี IE. (ง33105) : "))
    techno = float(input_grade_techno*1.0)
    input_grade_fun_eng = float(input("Fundamental English (อ33105) : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_math = float(input("คณิตศาสตร์ (ค32204) : "))
    math = float(input_grade_math*1.5)
    input_grade_extra_math2 = float(input("คณิตศาสตร์เพิ่มเติม (ค33205) : "))
    extra_math2 = float(input_grade_extra_math2*1.5)
    input_grade_physic = float(input("วิทยาศาสตร์(ฟิสิกส์) (ว32204) : "))
    physic = float(input_grade_physic*1.5)
    input_grade_physic2 = float(input("วิทยาศาสตร์(ฟิสิกส์) (ว33205) : "))
    physic2 = float(input_grade_physic2*1.5)
    input_grade_chemcical = float(input("วิทยาศาสตร์(เคมี) (ว32224) : "))
    chemcical = float(input_grade_chemcical*1.5)
    input_grade_biology = float(input("วิทยาศาสตร์(ชีววิทยา) (ว32244) : "))
    biology = float(input_grade_biology*1.5)
    input_grade_biology2 = float(input("วิทยาศาสตร์(ชีววิทยา) (ว33245) : "))
    biology2 = float(input_grade_biology2*1.5)
    input_grade_astronomy = float(input("โลก ดาราศาสตร์ และอวกาศ (ว32264) : "))
    astronomy = float(input_grade_astronomy*1.0)
    input_grade_pe2 = float(input("พลศึกษา (พ33205) : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_dev_eng = float(input("Developmental English (อ32203) : "))
    dev_eng = float(input_grade_dev_eng*1.0)
    input_grade_dev_eng2 = float(input("Developmental English (อ32204) : "))
    dev_eng2 = float(input_grade_dev_eng2*1.0)

def smap_m5_term2(): #พสพ ม.5 เทอม 2
    print("กลุ่มสาระการเรียนรู้พื่นฐาน")
    input_grade_thai = float(input("ภาษาไทยพื้นฐาน (ท33106) : "))
    thai = float(input_grade_thai*1.0)
    input_grade_math_ie = float(input("คณิตศาสตร์ IE. (ค33106) : "))
    math_ie = float(input_grade_math_ie*1.0)
    input_grade_science = float(input("วิทยาศาสตร์ IE. (ว33106) : "))
    science = float(input_grade_science*1.0)
    input_grade_social_ie = float(input("สังคมศึกษา ศาสนา และวัฒนธรรม IE. (ส33111) : "))
    social_ie = float(input_grade_social_ie*1.0)
    input_grade_religion = float(input("ศาสนา (ส33112) : "))
    religion = float(input_grade_religion*1.0)
    input_grade_pe1 = float(input("สุขศึกษา (พ31106) : "))
    pe1 = float(input_grade_pe1*0.5)
    input_grade_art = float(input("ศิลปะ (ศ33106) : "))
    art = float(input_grade_art*0.5)
    input_grade_techno = float(input("การงานอาชีพและเทคโนโลยี IE. (ง33106) : "))
    techno = float(input_grade_techno*1.0)
    input_grade_fun_eng = float(input("Fundamental English (อ33106) : "))
    fun_eng = float(input_grade_fun_eng*1.0)

    print("กลุ่มสาระการเรียนรู้เพิ่มเติม")
    input_grade_extra_math = float(input("คณิตศาสตร์เพิ่มเติม (ค33206) : "))
    extra_math = float(input_grade_extra_math*1.5)
    input_grade_physic = float(input("วิทยาศาสตร์(ฟิสิกส์) (ว33206) : "))
    physic = float(input_grade_physic*1.5)
    input_grade_chemcical = float(input("วิทยาศาสตร์(เคมี) (ว33225) : "))
    chemcical = float(input_grade_chemcical*1.5)
    input_grade_chemcical2 = float(input("วิทยาศาสตร์(เคมี) (ว33226) : "))
    chemcical2 = float(input_grade_chemcical2*1.5)
    input_grade_biology = float(input("วิทยาศาสตร์(ชีววิทยา) (ว33246) : "))
    biology = float(input_grade_biology*1.5)
    input_grade_astronomy = float(input("โลก ดาราศาสตร์ และอวกาศ (ว33265) : "))
    astronomy = float(input_grade_astronomy*1.0)
    input_grade_astronomy2 = float(input("โลก ดาราศาสตร์ และอวกาศ (ว33266) : "))
    astronomy2 = float(input_grade_astronomy2*1.0)
    input_grade_pe2 = float(input("พลศึกษา (พ33206) : "))
    pe2 = float(input_grade_pe2*0.5)
    input_grade_dev_eng = float(input("Developmental English (อ33205) : "))
    dev_eng = float(input_grade_dev_eng*1.0)
    input_grade_dev_eng2 = float(input("Developmental English (อ33206) : "))
    dev_eng2 = float(input_grade_dev_eng2*1.0)